import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { base44 } from "@/api/base44Client";
import { Loader2, Sparkles, Brain } from "lucide-react";
import { toast } from "sonner";

export default function AIWorkflowGenerator({ open, onOpenChange, onWorkflowGenerated, clientProfile }) {
  const [prompt, setPrompt] = useState("");
  const [generating, setGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setGenerating(true);
    
    try {
      const systemContext = `
        You are an expert ERPNext and Automation architect.
        Generate a JSON structure for an "ArkAutomation" workflow based on the user request.
        The output must strictly follow this schema structure:
        {
          "name": "String",
          "trigger": "manual" | "event" | "ai_prediction" | "schedule",
          "nodes": [Array of ReactFlow nodes],
          "edges": [Array of ReactFlow edges],
          "actions": [
             { "action_type": "SendEmail" | "UpdateDoc" | "CallAPI", "params": "{}", "order": 1, "enabled": true }
          ]
        }
        
        Nodes types available: 'trigger', 'action', 'condition', 'ai', 'delay', 'email', 'update'.
        Context: Client Industry: ${clientProfile?.industry_tag || 'General'}, Priority: ${clientProfile?.priority_area || 'Efficiency'}.
      `;

      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `${systemContext}\n\nUser Request: ${prompt}`,
        response_json_schema: {
           type: "object",
           properties: {
             name: { type: "string" },
             trigger: { type: "string" },
             nodes: { type: "array", items: { type: "object", additionalProperties: true } },
             edges: { type: "array", items: { type: "object", additionalProperties: true } },
             actions: { type: "array", items: { type: "object", additionalProperties: true } }
           },
           required: ["name", "nodes", "edges"]
        }
      });

      onWorkflowGenerated(res);
      onOpenChange(false);
      toast.success("Workflow generated by AI");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate workflow");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-500" />
            Generate Workflow with AI
          </DialogTitle>
          <DialogDescription>
            Describe the business process you want to automate. Our AI will design the workflow structure, triggers, and actions for you.
          </DialogDescription>
        </DialogHeader>

        <div className="py-4">
           <Textarea 
             placeholder="E.g., When a high-value lead is created, check sentiment with AI. If positive, assign to Sales Director and send a Slack notification. If negative, send a nurturing email."
             className="h-32"
             value={prompt}
             onChange={(e) => setPrompt(e.target.value)}
           />
           
           <div className="mt-4 bg-purple-50 p-3 rounded-lg border border-purple-100 flex gap-3">
              <Brain className="w-5 h-5 text-purple-600 shrink-0" />
              <div>
                 <p className="text-xs font-medium text-purple-800">AI Suggestion</p>
                 <p className="text-xs text-purple-600 mt-1">
                    Try: "Automate invoice follow-up. If invoice is overdue by 7 days, send reminder. If 30 days, alert finance manager."
                 </p>
              </div>
           </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button 
            onClick={handleGenerate} 
            disabled={generating || !prompt.trim()}
            className="bg-gradient-to-r from-purple-600 to-blue-600 text-white border-0"
          >
            {generating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Designing...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Workflow
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}